name: Test

on:
  workflow_call:

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Fetch Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test
